databases:
  - name: render
    plan: free
    databaseName: render
    user: render_y61u_user

services:
  - type: web
    plan: free
    name: projectPis
    runtime: python
    buildCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: python -m gunicorn projectPis.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
