# Generated by Django 5.2.1 on 2025-06-05 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codplanmejora', models.IntegerField()),
                ('codaccion', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('fechacompromiso', models.DateField()),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'acciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('codarchivo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('tipomime', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('fechacarga', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('codfacultad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'facultades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('codmodelo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'modelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleelementofundamentalfuentedeinformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codelementofundamental', models.IntegerField()),
                ('codfuentedeinformacion', models.IntegerField()),
            ],
            options={
                'db_table': 'detalleelementofundamentalfuentedeinformacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Escalavaloracion',
            fields=[
                ('codescalavaloracion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color_hex', models.TextField(blank=True, null=True)),
                ('valor_min', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'escalavaloracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('codestado', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('codevidencia', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evidencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('codinstitucion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicionelementofundamental',
            fields=[
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codelementofundamental', models.IntegerField()),
                ('codfuentedeinformacion', models.IntegerField()),
                ('codmedicionelementofundamental', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fechacorte', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicionelementofundamental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicionevidencia',
            fields=[
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codmodelo', models.IntegerField()),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codelementofundamental', models.IntegerField()),
                ('codfuentedeinformacion', models.IntegerField()),
                ('codmedicionelementofundamental', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'medicionevidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observacionindicador',
            fields=[
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codmodelo', models.IntegerField()),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codpuntajeindicador', models.BigIntegerField()),
                ('codobservacionindicador', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecharegistroevaluacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'observacionindicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodoevaluacion',
            fields=[
                ('codperiodoevaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'periodoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntajeindicador',
            fields=[
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codpuntajeindicador', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('metodo', models.TextField(blank=True, null=True)),
                ('fechaevaluacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puntajeindicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('codrol', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codplanmejora', models.IntegerField()),
                ('codaccion', models.IntegerField()),
                ('codseguimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('avance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seguimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocarrera',
            fields=[
                ('codtipocarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipocarrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoescala',
            fields=[
                ('codtipoescala', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipoescala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoevaluacion',
            fields=[
                ('codtipoevaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoindicador',
            fields=[
                ('codtipoindicador', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tipoindicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiporecomendacion',
            fields=[
                ('codtiporecomendacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tiporecomendacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('codusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.CharField(max_length=80)),
                ('userid', models.TextField(unique=True)),
                ('clave', models.TextField()),
                ('estadologin', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('codfacultad', models.OneToOneField(db_column='codfacultad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.facultades')),
                ('codcarrera', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterios',
            fields=[
                ('codmodelo', models.OneToOneField(db_column='codmodelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.modelos')),
                ('codcriterio', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'criterios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('codfacultad', models.OneToOneField(db_column='codfacultad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.carreras')),
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
            options={
                'db_table': 'evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcriterios',
            fields=[
                ('codmodelo', models.OneToOneField(db_column='codmodelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.criterios')),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subcriterios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planmejora',
            fields=[
                ('codfacultad', models.OneToOneField(db_column='codfacultad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.evaluaciones')),
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codplanmejora', models.IntegerField()),
                ('fechaaprobacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
            options={
                'db_table': 'planmejora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('codfacultad', models.OneToOneField(db_column='codfacultad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.evaluaciones')),
                ('codcarrera', models.IntegerField()),
                ('codevaluacion', models.IntegerField()),
                ('codvisita', models.IntegerField()),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
            ],
            options={
                'db_table': 'visitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('codmodelo', models.OneToOneField(db_column='codmodelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.subcriterios')),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estandar', models.TextField(blank=True, null=True)),
                ('umbralminimo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('formulacalculo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Elementofundamental',
            fields=[
                ('codmodelo', models.OneToOneField(db_column='codmodelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.indicadores')),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codelementofundamental', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'elementofundamental',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fuentedeinformacion',
            fields=[
                ('codmodelo', models.OneToOneField(db_column='codmodelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.indicadores')),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codfuentedeinformacion', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'fuentedeinformacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineamientovariable',
            fields=[
                ('codmodelo', models.OneToOneField(db_column='codmodelo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='appPis.indicadores')),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codlineamientovariable', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'lineamientovariable',
                'managed': False,
            },
        ),
    ]
