# Generated by Django 5.2.1 on 2025-07-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracionelementofundamentalfuentedeinformaciondocumentos',
            fields=[
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codelementofundamental', models.IntegerField()),
                ('codfuentedeinformacion', models.IntegerField()),
                ('coddetalleelementofundamentalfuentedeinformacion', models.BigIntegerField()),
                ('coddconfiguracionelementofundamentalfuentedeinformaciondocument', models.BigAutoField(db_column='coddconfiguracionelementofundamentalfuentedeinformaciondocument', primary_key=True, serialize=False)),
                ('aplicavariosperiodos', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'configuracionelementofundamentalfuentedeinformaciondocumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.TextField(blank=True, null=True)),
                ('idnivel', models.IntegerField(blank=True, null=True)),
                ('nombrecortofacultad', models.TextField(blank=True, null=True)),
                ('nombrecarrera', models.TextField(blank=True, null=True)),
                ('curso', models.TextField(blank=True, null=True)),
                ('nombredocente', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('emailpersonal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Est',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.TextField(blank=True, null=True)),
                ('idfacultad', models.IntegerField(blank=True, null=True)),
                ('idnivel', models.IntegerField(blank=True, null=True)),
                ('nombrecortofacultad', models.TextField(blank=True, null=True)),
                ('nombrecarrera', models.TextField(blank=True, null=True)),
                ('curso', models.TextField(blank=True, null=True)),
                ('nombreestudiante', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('celular', models.TextField(blank=True, null=True)),
                ('emailpersonal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'est',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medidorelementofundamentalfuenteinformciondocumentos',
            fields=[
                ('codmodelo', models.IntegerField()),
                ('codcriterio', models.IntegerField()),
                ('codsubcriterio', models.IntegerField()),
                ('codindicador', models.IntegerField()),
                ('codelementofundamental', models.IntegerField()),
                ('codfuentedeinformacion', models.IntegerField()),
                ('coddetalleelementofundamentalfuentedeinformacion', models.BigIntegerField()),
                ('codmedidorelementofundamentaldocumentos', models.BigAutoField(primary_key=True, serialize=False)),
                ('aplicavariosperiodos', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'medidorelementofundamentalfuenteinformciondocumentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsablesindicador',
            fields=[
                ('codresponsable', models.AutoField(primary_key=True, serialize=False)),
                ('codfacultad', models.IntegerField(blank=True, null=True)),
                ('codcarrera', models.IntegerField(blank=True, null=True)),
                ('nombrecarrera', models.TextField(blank=True, null=True)),
                ('codindicador', models.IntegerField(blank=True, null=True)),
                ('nombreindicador', models.TextField(blank=True, null=True)),
                ('responsable', models.TextField(blank=True, null=True)),
                ('identificacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'responsablesindicador',
                'managed': False,
            },
        ),
    ]
